### ISSUE TITLE
The active font color is only selected in the document colors

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-font#51]
This seems wrong to me. Because you will never see the checkmark in the normal grid. It will always be in the document colors.

![image](https://user-images.githubusercontent.com/156149/60243978-bf750600-98b9-11e9-9531-3c3cce5ae29e.png)

**Comment by msamsel** [comment]
@Reinmar It was decided to have only one checkbox:
https://github.com/ckeditor/ckeditor5-font/issues/28#issuecomment-492597270
And you can see checkmark in normal grid if you have more colors than document color limit.
For example:
![Screenshot 2019-06-27 at 09 16 24](https://user-images.githubusercontent.com/9017322/60245188-5b077600-98bc-11e9-9292-634adf326baf.png)

**Comment by oleq** [comment]
IMO they should both have checkmarks (like in Sketch)

<img width="246" alt="Screenshot 2019-06-28 at 11 47 18" src="https://user-images.githubusercontent.com/1099479/60333966-b27c1380-999a-11e9-92e8-4f8e2a725e69.png">

**Comment by Reinmar** [comment]
Are there any arguments for not selecting both items?

**Comment by Reinmar** [comment]
cc @mlewand @dkonopka who were involved in the initial discussion.

**Comment by mlewand** [comment]
It was actually my suggestion to implement it with a single checkmark. The reason is that we have a relatively heavy way to indicate selected color and having both of these looked heavy/messy.

@msamsel can you check out to a version before this change and provide a screen of a **entire** editor with a dropdown where both colors are selected? And next to it put a current screen (with only one selected) so we can compare it.

**Comment by msamsel** [comment]
![Screenshot 2019-07-11 at 14 52 40](https://user-images.githubusercontent.com/9017322/61052420-a147f380-a3eb-11e9-9cf0-3e459e6f17bb.png)
![Screenshot 2019-07-11 at 14 53 05](https://user-images.githubusercontent.com/9017322/61052421-a147f380-a3eb-11e9-81c7-257fc52dd8ae.png)

**Comment by oleq** [comment]
I'm for the later.
